### ISSUE TITLE
Fields Name

### ISSUE THREAD

**Issue by jmbelloteau** [Wixel/GUMP#179]
Hi there,

Is there anyway to use **set_field_name()** with an array like this:

```
$fieldName= [
    'firstname' => 'prénom',
    'lastname' => 'nom',
     'email' => 'email',
     'phone' => 'téléphone',
     'message' => 'message'
];

$validator = new GUMP($lang);
$validator->set_field_name($fieldName);
```

It doesn't work like this

**Comment by filisko** [comment]
To do that you must use **set_field_names** method (see last **s**), just add the "s".

**Comment by jmbelloteau** [comment]
amazing :)

**Comment by filisko** [comment]
Thank you @jmbelloteau.
Cheers, Filis

**Comment by jimblue** [comment]
Hi @filisko  !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @filisko !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

**Comment by jimblue** [comment]
Hi @filisko !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

Cheers
