### ISSUE TITLE
Rule {} does not have an error message

### ISSUE THREAD

**Issue by RonaldoSantana** [Wixel/GUMP#180]
Gump keeps randomly raising the error on get_readable_errors.
It is just random - one second it can find the message the other cannot.

**Comment by filisko** [comment]
Could you detail your problem please?

**Comment by lchambers** [comment]
I'm getting the same error and I'm running it on PHP 7.0.15.

I've extended GUMP into my own class and within it I call the run method and if it fails then I call the get_errors_array method to carry out my own error message processing.

It's throwing the following error within that method: 

`PHP Fatal error:  Uncaught Exception: Rule "validate_required" does not have an error message in /vendor/wixel/gump/gump.class.php:631`

I've tried to debug it myself and I can't seem to work out what's going on with it. Within the get_errors_array method there's a "foreach ($this->errors as $e)" loop and dumping the messages array up until the error is thrown, it shows the messages array just fine, but just before it throws it dumps the variable as a bool(true).

It's an odd one...

**Comment by lchambers** [comment]
Update: I finally figured out what was going on.

If you validate 1 set of data and then validate another set, which is completely different, straight after then that's when it throws the error.

It's happening due to the the language file being included using require_once, within the get_messages method - line 522. As it's already been included the first time the validation is run on the second validation it returns bool(true), as I was dumping out.

If I include the method within my extended class, update the path variables to the file and then change this to "require_once" to "require" it no longer throws the error.

I hope that helps.

**Comment by filisko** [comment]
Thank you very much @lchambers !
