### ISSUE TITLE
Value data as array seems to be ignored

### ISSUE THREAD

**Issue by HarroH** [Wixel/GUMP#184]
Hi there,

First of all, very nice class. Worked great. Just seem to have an issue with my custom validator.

I'm trying to count the amount of row within an array. So my basic is_valid statement will look something like this:
```
<?php
$validation = GUMP::is_valid( array (
    
    ['dates'] => array (
		[0] => 2017-01-04 00:00:00
		[1] => 2017-01-05 00:00:00
	)

), array(
	
	'dates' => 'array_exact_len,3'

));
?>
```
I have this custom validator to check the lenght.

Custom Validator:
```
<?php
GUMP::add_validator( "array_exact_len", function( $field, $input, $param = NULL ) {
	
	echo '$field';
	print_r($field);
	
	echo '$input';
	print_r($input);
	
	echo '$param';
	print_r($param);
	
	die();
	
	//return ( count( $input[$field] ) === $param );
	
}, 'Not enough selected' );
```

I added some debug print_r's. When the 'dates' array is empty, the $field, $input and $param are returned properly. However, when the 'dates' array is filled with 1 or more rows, it will not output anything or throwback an error. It will just say it's valid (true).

Are array's not supported as value or I'm I doing something wrong?

**Comment by filisko** [comment]
Hi @HarroH,

I will try to have something for this week, I already have something in local and it's nearly finished.

**Comment by HarroH** [comment]
Great. I now solved it to convert the array to json and convert is back to an array in the validator. But not sure if that is a very nice solution. But for now it works. Looking forward to your outcome.

**Comment by filisko** [comment]
Hi @HarroH, the functionality I implemented now is actually not valid for your case, it allows you to validate and filter data arrays like yours, but because of the approach being used in the library, when array input is entered, instead of passing the array to the validate method (it would break all our validators and to fix it all the validators would have to check if it's an array and do a loop every time!), we pass instead one-by-one the values of the array to the validator.

So arrays are supported, yes, but you don't get the array of the field in your validation method.

**Comment by HarroH** [comment]
Hoi Filisko, thanks for the reply and looking into it. As I need to could the amount of rows in my array I need it in the method. So I will stick with the json_decode en encode then instead to go around the issue. Thanks again for the time.

**Comment by filisko** [comment]
@HarroH , no problem !
Thanks for your patience :smile:
