### ISSUE TITLE
Alpha_dash filter..can anyone verify please?

### ISSUE THREAD

**Issue by 10Pound** [Wixel/GUMP#209]
Hi, nice class, I've been checking it out.

Can someone verify or confirm this filter behavior, please?

According to the docs, Alpha_dash is defined as 'Ensure only alpha-numeric characters + dashes and underscores are present in the key value (a-z, A-Z, 0-9, _-)'.  I've run a number of tests and I keep getting the same incorrect response.  In short, a post containing a 16 character string value made up of alphanumeric and hyphen/dash characters like so 'AB-CDEF-GHI-JKLM'.  The validation rule applied to this value is 'required|alpha_dash|max_len,16|min_len,16'.  However, regardless of any processing done before or after to this value, after running it through the validation process, it returns false with get_errors_ array() stating 'The <whatever> field may only contain letters and dashes.  If I remove alpha_dash from the validation rule set, it works fine.

**Comment by eko3alpha** [comment]
Following your rules, this is what I got.

get_errors_array() should never return a boolean value.  It will either return an empty array [] or an array with error messages.  

In your case, you should return an empty array [] since your input of "AB-CDEF-GHI-JKLM" will provide no errors.

```
$gump = new GUMP();

$_POST = ["id"=>"AB-CDEF_GHI-JKLM"];

$gump->validation_rules(['id' => 'required|alpha_dash|max_len,16|min_len,16']);

$gump->run($_POST);

$gump->get_errors_array(); // returns [] since input passes validation rules

```

This example has errors

```
$gump = new GUMP();

$_POST = ["id"=>"AB-CDEF_#HI-JKLM"];

$gump->validation_rules(['id' => 'required|alpha_dash|max_len,16|min_len,16']);

$gump->run($_POST);

$gump->get_errors_array(); //  ['id' =>"The Id field may only contain letters and dashes"]

```

I'm not seeing an issue with the rule, it appears to be working as expected.  I would suggest you use "exact_len,16" instead of using both min/max length rules.

I can only speculate that your logic is wrong elsewhere.  You say you returned "false" for get_errors_array().  Have you actually validated this by checking the output of the method?  Or are you making this assumption on the conditional logic around the method itself?

Here is what I mean.   If you are checking your form for errors by doing something like this.

```
if( $gump->get_errors_array() == false )  // reads something like -> there are no any errors
{
    echo "There are errors!";  // but there are errors... 
} else {
    echo "There are no errors";  // nope there isnt
}
```

Are you doing something similar and assuming it's returning false because you are checking for false?  This is a contrived example but the only one I can think of given your example.

**Comment by filisko** [comment]
But docs were wrong. alpha_numeric_dash is added to TODO list.
