### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by shuxx** [Wixel/GUMP#95]
Hello why not translate errors messages ? 
i'm volonter for french :)

**Comment by Hirbod** [comment]
me for german

**Comment by SeanNieuwoudt** [comment]
Great! If you go through the error fields in the code and create the translated error text, I'll gladly create a mechanism for it.

**Comment by Hirbod** [comment]
First of all:

29 languages with (noise/stopwords)
https://code.google.com/p/stop-words/

**Comment by Hirbod** [comment]
Second:

I guess it should be the better way when you provide the mechanism first. Currently, your validation text is hardcoded. So if I translate it, I would duplicate that file, change all the strings and send it to you. You will have to copy&paste everything into your new mech. I guess you should provide some kind of language files (maybe I18n based) and use formatters, include the mech, publish your default english file and then we will start to translate. :)

**Comment by SeanNieuwoudt** [comment]
Good point - Ok, I'll work on adding some kind of extendible mechanism to facilitate the translation process. Give me a few days to put that together though.

**Comment by neurotools** [comment]
Count me in for spanish. Any timeline for this? Need ideas or help?

**Comment by wwwjsw** [comment]
me for Portuguese!

**Comment by dlplanet** [comment]
me for persian!

**Comment by shuxx** [comment]
Some news for translation ?

**Comment by jmbelloteau** [comment]
Any news about an update with mechanism for translation? Many people here are ready to translate and share 😄  !

**Comment by jmbelloteau** [comment]
I mean this issue is almost open for two years now... just saying 😅

**Comment by filisko** [comment]
Hi guys,

I will have something in next couple of days.

How do you think that it should be done ? @shuxx @jmbelloteau

**Comment by shuxx** [comment]
I don't have any solution to purpose but i can help to translate...

**Comment by jmbelloteau** [comment]
Same as @shuxx , I need a translation in french and I would be happy to share it. But I have no idea how to make the magic...

**Comment by shuxx** [comment]
First of all, we need a mechanism anyone know solutions?

**Comment by filisko** [comment]
Ok, I will be thinking on it just now.

**Comment by jmbelloteau** [comment]
This validation library have translation maybe it could give some hint @filisko ??

[VALITRON LIBRARY](https://github.com/vlucas/valitron)

**Comment by filisko** [comment]
Ok, I will be thinking on it just now. I have some ideas, just wanted to know if you had already any ideas.

**Comment by shuxx** [comment]
@Filisko your the owner of gump or u will make a pull request ?

**Comment by filisko** [comment]
@shuxx, I'm a collaborator of this project, I will think later about how to don't breaking anything :laughing:, now I'm just thinking about the code to support languages.

**Comment by jmbelloteau** [comment]
Amazing @shuxx  !

Count on me for french translation as soon as we'll make magic happen. 😄

**Comment by shuxx** [comment]
@Filisko i just say that because the project didn't move from 6 month

**Comment by filisko** [comment]
@shuxx let's move it then :smile:

**Comment by filisko** [comment]
Just [released 1.5](https://github.com/Wixel/GUMP/releases/tag/1.5)  with backwards compatibility that includes multilingual support.

Have a look!

**Comment by shuxx** [comment]
Greet let's to it!

**Comment by jmbelloteau** [comment]
Amazing @filisko ! That was pretty fast 😄 !

I've tried to update with composer but didn't work, I guess you will do it soon.
So I've download the archive I just have no idea how to change language...

**Comment by filisko** [comment]
Hi @jmbelloteau, I would actually tell you download it again! Just added few fixes in the last minutes.

You can switch the language like that:
```php
$lang = 'en';
$gump = new GUMP($lang);
```

**Comment by jmbelloteau** [comment]
cool
here is the french translation, you can add it to the repo so it will be easier tho make it better for every frenchy :)

[french translation](https://gist.github.com/jmbelloteau/e1c2246e9fc03c7d5c2e850bdbf70130)

**Comment by jmbelloteau** [comment]
Does composer work now?

**Comment by jmbelloteau** [comment]
Just made it work, it's really cool 😄  !
I just see something that cool be better:

{field} is not translate with this system... So the response is a mix of the input name and the translated language...

**Comment by filisko** [comment]
Remember that you can use something like that:
```php
GUMP::set_field_name('username, 'Username');
```
To customize the {field} message.

**Comment by filisko** [comment]
Open a new issue if you need to @jmbelloteau 

Cheers

**Comment by jmbelloteau** [comment]
ok thanks!

**Comment by jimblue** [comment]
Hi @filisko  !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

PS: your website seems to be down

**Comment by rifton007** [comment]
Hi everybody,
For me, the transalation in french doesn't display correctly.
The Codes ASCII isn't escaped and display juste the code. So that I have nothing problem in my website with special characters. Somebody does have the same problem that me ?

Thanks,

![capture](https://user-images.githubusercontent.com/2601347/36268275-57a58a7e-1276-11e8-835f-3941333eddf6.PNG)

**Comment by jimblue** [comment]
Hi @filisko !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

I'll remove this message once it's done!

Cheers

PS: your website seems to be down

**Comment by jimblue** [comment]
@filisko !

Has you can see I've change my Github user name for jimblue. Keeping jmbelloteau was not good for SEO as my website is jmbelloteau.com and I started to have many post on Github.

Because Github doesn't do it automatically could you please guy change the reference to @jmbelloteau for @jimblue in your post above?

Thank you for helping me with that.

Cheers

PS: your website seems to be down

**Comment by filisko** [comment]
Done @jimblue! Sorry for the delay
